application: udacity-game-design
version: 1
api_version: 1
runtime: python27
threadsafe: true

handlers:

- url: /static
  static_dir: static
- url: /
  static_files: static/index.html
  upload: static/index\.html
  secure: always

- url: /_ah/spi/.*
  script: game_api.APPLICATION
  secure: always
  
- url: /tasks/send_invite_email
  script: main.app

- url: /crons/send_test_cron
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: endpoints
  version: 1.0

