application: udacity-game-design
version: 1
api_version: 1
runtime: python27
threadsafe: true

handlers:

- url: /style
  static_dir: style
  
- url: /scripts
  static_dir: scripts
  
- url: /content
  static_dir: content

- url: /_ah/spi/.*
  script: game_api.APPLICATION
  secure: always
  
- url: /tasks/.*
  script: main.app

- url: /crons/send_test_cron
  script: main.app
  
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: endpoints
  version: 1.0
- name: jinja2
  version: latest

