api_version: 1
runtime: python27
threadsafe: true

handlers:

- url: /static
  static_dir: static

- url: /_ah/spi/.*
  script: src.game_api.APPLICATION
  secure: always
  
- url: /tasks/.*
  script: main.app

- url: /crons/send_test_cron
  script: main.app
  
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: endpoints
  version: 1.0
- name: jinja2
  version: latest

